name: TAF AGENCY
favicon: null
layout_spectrum: 0.87959
typography_spectrum: 0.40337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#956e26'
    - '#000000'
    - '#800000'
    - '#ff0000'
    - '#804000'
  brandStrength: 0.125
  lightness: 0.8925216153729707
  saturation: 0.13798096752725542
  rhythmicContrast: 0.8441204379778355
purpose: []
