name: TAF AGENCY
favicon: null
layout_spectrum: 0.1648773248307407
typography_spectrum: 0.826192710082978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.19937855354510248
  lightness: 0.8925216153729707
  saturation: 0.13798096752725542
  rhythmicContrast: 0.8441204379778355
purpose: []
